### ISSUE TITLE
Cowrie log bugs

### ISSUE THREAD

**Issue by yevonnaelandrew** [telekom-security/ewsposter#10]
There are bugs in ews.py, so it does not parse the input commands. 

Before:
` if line['eventid'] == 'cowrieSession.command.input' and line['session'] in cowrieSessions:`
It should be:
`if line['eventid'] == 'cowrie.command.input' and line['session'] in cowrieSessions:`

But it still only records one command, which in this case will be the last command inputted. So we need to add conditions to accommodate multiple commands.

**Comment by trixam** [comment]
Thanx. Merged. Closed
